### ISSUE TITLE
[Bug]: fixed position is not preserved across reboots

### ISSUE THREAD

**Issue by IZ1IVA** [meshtastic/Meshtastic-device#1811]
### Category

Other

### Hardware

T-Beam, T-Lora v2 1.6

### Firmware Version

1.3.44-45

### Description

When setting a fixed position, first I disable the GPS with `position.gps_enabled`, then reboot to make sure GPS stays off. I then set the position with `--setalt --setlat --setlon` and that works as expected.
However, a further reboot will set altitude, latitude and longitude to zero.
This is particularly inconvenient for remote nodes without GPS (e.g. T-Loras).

**Comment by IZ1IVA** [comment]
> @IZ1IVA can you try updating to the the latest python cli version? I suspect this change might have resolved it: [meshtastic/Meshtastic-python#385](https://github.com/meshtastic/Meshtastic-python/pull/385)

I will! I'm sorry I've tried yesterday without first checking for an updated Python CLI...

**Comment by caveman99** [comment]
I have a Router Node based on TLORA-2.1-1.6 running more or less 'Master' and it has he fixed position fine and keeps it across reboots and firmware updates.

```
config:
[...]
  position:
    fixedPosition: true
    gpsAttemptTime: 900
    gpsUpdateInterval: 120
    positionBroadcastSecs: 900
    positionFlags: 3
[...]
location:
  alt: 170
  lat: 50.<redacted>
  lon: 6.<redacted>
[...]
```
